

- name: Create a system user for "{{ component }}"
  ansible.builtin.user:
    name: roboshop
    comment: roboshop system user
    system: true
    shell: /sbin/nologin
    home: /app

- name: Recursively remove directory
  ansible.builtin.file:
    path: /app
    state: absent

- name: Remove existing "{{ component }}".zip file
  ansible.builtin.file:
    path: /tmp/"{{ component }}".zip
    state: absent

- name: create directory
  ansible.builtin.file:
    name: /app
    state: directory

- name: Download appliction to app directory
  ansible.builtin.get_url:
    url: https://roboshop-artifacts.s3.amazonaws.com/{{ component }}-v3.zip 
    dest: /tmp/{{ component }}.zip

- name: Unzip "{{ component }}".zip that is already on the remote machine
  ansible.builtin.unarchive:
    src: /tmp/{{ component }}.zip
    dest: /app
    remote_src: yes
