- name: Setup the MongoDB repo file
  ansible.builtin.copy:
    src: mongo.repo
    dest: /etc/yum.repos.d/mongo.repo

- name: Install mongo db
  ansible.builtin.package:
    name: mongodb-org
    state: present

- name: Update listen address
  ansible.builtin.replace:
    path: /etc/mongod.conf
    regexp: '127.0.0.1'
    replace: '0.0.0.0'

- name: Enable mongo service
  ansible.builtin.service:
    name: mongod
    enabled: true
    state: started